#!/usr/bin/env bash
if [ $# -eq 0 ]; then
  osascript <<< "
    tell application \"iTerm2\"
      create window with default profile
    end tell
  "
else
  osascript <<< "
    tell application \"iTerm2\"
      create window with default profile command \"$*\"
    end tell
  "
fi
